name: CI to Docker Registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true
  
jobs:

  frontend:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Private Docker Registry
        uses: docker/login-action@v1
        with:
          registry: private.docker.gillespie.eu
          username: ${{ secrets.CI_BOT_USERNAME }}
          password: ${{ secrets.CI_BOT_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            private.docker.gillespie.eu/repository/gillespie-private-docker/bsc-thesis-frontend:${{ github.event.inputs.version }}
            private.docker.gillespie.eu/repository/gillespie-private-docker/bsc-thesis-frontend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
        
  backend:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Private Docker Registry
        uses: docker/login-action@v1
        with:
          registry: private.docker.gillespie.eu
          username: ${{ secrets.CI_BOT_USERNAME }}
          password: ${{ secrets.CI_BOT_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            private.docker.gillespie.eu/repository/gillespie-private-docker/bsc-thesis-backend:${{ github.event.inputs.version }}
            private.docker.gillespie.eu/repository/gillespie-private-docker/bsc-thesis-backend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
